services:
  - type: web
    name: warehouse-tracker-backend
    runtime: python
    preDeployCommand: "./scripts/render_predeploy.sh"
    buildCommand: "pip install . && pip install gunicorn django-cors-headers whitenoise && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate --noinput && gunicorn config.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: warehousetracker-1.onrender.com,warehouse-tracker-backend.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://warehousetracker-1.onrender.com,https://warehouse-tracker-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://warehouse-tracker-lemon.vercel.app,https://warehousetracker-1.onrender.com
